events {}

http {
    server {
        listen 8080;

        location / {
            include fastcgi_params;
            fastcgi_pass fastcgi_app:81;
            fastcgi_param SCRIPT_FILENAME /app/server;
        }

        location /status {
            stub_status;
        }
    }
}

