services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastcgi_app
    networks:
      - app_net

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

